spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: ********@qq.com
    password: ********
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true

